export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  admin: '/admin',
  superAdmin: '/super-admin',
  instructor: {
    dashboard: '/instructor/dashboard',
    classes: '/instructor/classes',
    classManage: (classId: number | string) => `/instructor/classes/${classId}`,
    classMembers: (classId: number | string) => `/instructor/classes/${classId}/members`,
    classQuizzes: (classId: number | string) => `/instructor/classes/${classId}/quizzes`,
    studio: '/instructor/studio',
    studioQuiz: '/instructor/studio/quiz',
    studioMaze: '/instructor/studio/maze',
    studioSnake: '/instructor/studio/snake',
    studioBreakout: '/instructor/studio/breakout',
    studioRace: '/instructor/studio/race',
    performance: '/instructor/performance',
    library: '/instructor/library',
    libraryQuizEdit: (quizId: number | string) => `/instructor/library/quiz/${quizId}/edit`,
    settings: '/instructor/settings',
  },
  student: {
    dashboard: '/student/dashboard',
    classes: '/student/classes',
    join: '/student/join',
    courses: '/student/courses',
    coursesWithClass: (classId: number | string) => `/student/courses?class=${classId}`,
    quiz: '/student/quiz',
    quizSession: (classId: number | string, quizId: number | string) =>
      `/student/quiz/${classId}/${quizId}`,
    grades: '/student/grades',
    gameMaze: '/student/games/maze',
    gameSnake: '/student/games/snake',
    gameBreakout: '/student/games/breakout',
    gameRace: '/student/games/race',
    settings: '/student/settings',
  },
} as const
